// Code generated by goctl. DO NOT EDIT.
package types

type RegisterRequest struct {
	Name             string `json:"name"`
	Mobile           string `json:"mobile"`
	Password         string `json:"password"`
	VerificationCode string `json:"berification_code"`
}

type RegisterResponse struct {
	UserId int64 `json:"user_id"`
	Token  Token `json:"token"`
}

type Request struct {
	Name string `path:"name,options=you|me"`
}

type Response struct {
	Message string `json:"message"`
}

type Token struct {
	AccessToken  string `json:"access_token"`
	AccessExpire int64  `json:"access_expire"`
}

type VerificationRequest struct {
	Mobile string `json:"mobile"`
}

type VerificationResponse struct {
}
